import {PDFDocument,StandardFonts,PDFName,PDFString} from 'pdf-lib';
import {processPdf,pdfTool} from '../src/engines/pdf';
import {DEFAULT_OPTIONS} from '../src/core/types';
const log=(message:string)=>{document.querySelector('#results')!.textContent+='\n'+message;};
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);log('PASS '+message);};
const options={...DEFAULT_OPTIONS,format:'pdf' as const,maxBytes:1,stripMetadata:false,minQuality:.85};
async function fixture(){const doc=await PDFDocument.create();const font=await doc.embedFont(StandardFonts.Helvetica);const page=doc.addPage([300,500]);page.drawText('FileFit TEXT PRESERVED 123',{font,size:16,x:20,y:440});const link=doc.context.register(doc.context.obj({Type:'Annot',Subtype:'Link',Rect:[20,430,270,460],Border:[0,0,0],A:{S:'URI',URI:PDFString.of('https://example.com')}}));page.node.set(PDFName.of('Annots'),doc.context.obj([link]));return new File([new Uint8Array(await doc.save())],'verification.pdf');}
document.querySelector('#run')!.addEventListener('click',async()=>{document.querySelector('#results')!.textContent='Running';const signal=new AbortController().signal;
try{const file=await fixture();const output=await processPdf(file,options,(_v,m)=>log(m),signal);const doc=await PDFDocument.load(await output.blob.arrayBuffer());assert(doc.getPageCount()===1&&doc.getPage(0).getWidth()===300,'compression preserves page dimensions');assert(doc.getPage(0).node.Annots()?.size()===1,'compression preserves link annotation');const texts=await pdfTool([new File([output.blob],'compressed.pdf')],'text',options,()=>{},signal);assert((await texts[0].blob.text()).includes('TEXT PRESERVED'),'compression preserves extractable text');
const password='test"\\pass123';const [encrypted]=await pdfTool([file],'encrypt',{...options,outputPassword:password},()=>{},signal);assert(encrypted.info.encrypted,'AES encryption');let rejected=false;try{await pdfTool([new File([encrypted.blob],'locked.pdf')],'decrypt',{...options,password:'wrong'},()=>{},signal);}catch{rejected=true;}assert(rejected,'incorrect password rejected');const [decrypted]=await pdfTool([new File([encrypted.blob],'locked.pdf')],'decrypt',{...options,password},()=>{},signal);assert((await PDFDocument.load(await decrypted.blob.arrayBuffer())).getPageCount()===1,'correct password with quote and slash decrypts');
const cancellation=new AbortController();const promise=processPdf(file,options,()=>{},cancellation.signal);setTimeout(()=>cancellation.abort(),100);let cancelled=false;try{await promise;}catch(e){cancelled=e instanceof DOMException&&e.name==='AbortError';}assert(cancelled,'active worker cancellation');log('ALL PDF CHECKS PASSED');
}catch(e){log('FAIL '+(e instanceof Error?e.stack:e));}});
document.querySelector('#ocr')!.addEventListener('click',async()=>{document.querySelector('#results')!.textContent='OCR running';try{const result=await pdfTool([await fixture()],'ocr',{...options,maxBytes:0,ocrLanguage:'eng'},(_v,m)=>log(m),new AbortController().signal);assert(result.length===2,'OCR yields searchable PDF and text');assert((await result[1].blob.text()).includes('FileFit'),'English OCR recognizes sample');const doc=await PDFDocument.load(await result[0].blob.arrayBuffer());assert(doc.getPage(0).getWidth()===300&&doc.getPage(0).getHeight()===500,'OCR preserves page size');log('ALL OCR CHECKS PASSED');}catch(e){log('FAIL '+(e instanceof Error?e.stack:e));}});
